# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Curly Lab
url:              https://curlylab.com

paginate:         6

# excerpt_separator: <!--more-->

# version:          1.0.5
